### PR TITLE
Rebranding

### PR DESCRIPTION
**Pull request by dialex**
We should create a unique design for our extension. The current logo is a straight copy of Cucumber's logo. That's confusing and not very informative.

We can use it as an **opportunity for rebranding**.

The goal of this extension is to provide snippets of Gherkin syntax. Snippets... Templates... Recipes... Cucumber Recipes! Then we could call our extension: _"Cucumber Cookbook - Snippets and other useful templates"_

If we want to rebrand our name, then I recommend [logo4](https://github.com/stevejpurves/vscode-cucumber/blob/ca953ed783935cefd279760563d843a60ca60ec5/images/logo4-highres.png).
If we stick to the existing name, then I recommend [logo](https://github.com/stevejpurves/vscode-cucumber/blob/ca953ed783935cefd279760563d843a60ca60ec5/images/logo-highres.png).

Can you check both and tell me which one you prefer?

P.S: Please don't approve yet this PR, just comment.

### CODE REVIEW

**Comment by dialex** [comment]
A week(end) has passed, do you have any update @stevejpurves ?

**Comment by stevejpurves** [comment]
logo4 looks good @dialex and why not change the name to reflect a new start :)

**Comment by stevejpurves** [comment]
@dialex you might want to also think about how the publisher name appears on the vscode marketplace.

**Comment by dialex** [comment]
AWESOME!! Will do.
I still need you to explain how I can publish to vscode. And I think I also need the permissions.
But we can discuss that through email (please).

**Pull request merged**
