### PR TITLE
Markdown syntax highlighting

### LINKED ISSUE #26: syntax highlighting for markdown-embedded gherkin
I'm using `yzhang.markdown-all-in-one` for previewing markdown files. This works a treat for automagically applying syntax highlighting to both the plain-text and the generated output.

This plugin seems to have some mechanism for picking up installed syntax highlighters based on the tags on markdown code blocks. I usually find that installing an appropriate plugin Just Works (for python, plantuml, Rust, etc.)

Is there some way to register this plugin as a syntax highlighter for these embedded code blocks?

apologies for not providing more detail, i'm really not clear on how this is implemented for other 'languages'. Hoping you'll know more than me

### PR DESCRIPTION
**Pull request by danieleades**
closes #26

### CODE REVIEW

**Comment by danieleades** [comment]
it can't possibly be this simple, can it???

**i haven't tested this change whatsoever**. I've never worked on a vscode extension before. How does one test it?

looks like the syntax is already registered by this extension as 'feature', rather than 'gherkin'. I've not touched this. (see https://github.com/euclidity/vscode-cucumber/issues/26#issuecomment-739366496)

**Comment by dialex** [comment]
Honestly, me neither. I'm a maintainer but I'm not the author. I know I shouldn't but I'll test this in production 😬

**Comment by dialex** [comment]
It didn't work, the code block still has no syntax highlight. It kind makes sense, because probably you have to specify the format/color of each word, so it can't be just a one liner on package.json:

Screenshot 2020-12-12 at 18 09 41

Nice try tho. I'll revert it now.

**Comment by dialex** [comment]
So I tried to [follow these steps](https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example), and released a 0.13.2 version. (testing now) ⏳

**Comment by danieleades** [comment]
> It didn't work, the code block still has no syntax highlight. It kind makes sense, because probably you have to specify the format/color of each word, so it can't be just a one liner on package.json:

Really? I'm not trying to *implement* syntax highlighting (the plugin already does this for `.feature` files) I'm just trying to inject it into markdown

**Comment by dialex** [comment]
Right, notice my screenshot, it's a markdown file. And you want to have syntax highlight inside that ```feature code block right?

**Comment by danieleades** [comment]
> Right, notice my screenshot, it's a markdown file. And you want to have syntax highlight inside that ```feature code block right?

That's the plan...

Like I said, I don't know a thing about vscode extensions. Basically black magic to me

**Pull request merged**
